/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Codemon */

#ifndef _Included_Codemon
#define _Included_Codemon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Codemon
 * Method:    parse
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Codemon_parse
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     Codemon
 * Method:    runTest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Codemon_runTest
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     Codemon
 * Method:    runSelf
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Codemon_runSelf
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     Codemon
 * Method:    runPVP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_Codemon_runPVP
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     Codemon
 * Method:    getReport
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Codemon_getReport
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
